name: ci

on:
  schedule:
    - cron: 30 12 * * 1
  push:
    paths:
      - Dockerfile
      - .github/workflows/build.yaml
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get latest ledfx version
        id: version
        run: |
          echo "LEDFX_VERSION=$(curl -Ls https://pypi.org/pypi/ledfx/json | jq -r .info.version)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/explodingcamera/ledfx

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            ghcr.io/explodingcamera/ledfx:latest
            ghcr.io/explodingcamera/ledfx:${{ steps.version.outputs.LEDFX_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
